services:
  db-postgres:
    image: postgres:15
    container_name: django-test-db
    environment:
      POSTGRES_DB: django_test
      POSTGRES_USER: django_test
      POSTGRES_PASSWORD: 1234
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin-v2:
    image: dpage/pgadmin4
    container_name: django-test-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5445:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin4
volumes:
  postgres_data:
  pgadmin_data:
networks:
  default:
    driver: bridge
